Stop combat release kick when player cannot manoverboard
TylerS1066/Movecraft-Combat pull request #46
Opened 2021-01-03 02:22 UTC by HumorousFool

This PR adds a check to see whether the craft is disabled, in another world or out of range of the pilot's manoverboard range.

2021-01-03 23:11 UTC, TylerS1066 requested changes
I like this solution, but in the future I would prefer that we open issues to discuss changes like this before coding them (in the case where they are not wanted).

There are some slight edits I'd like to have made to improve performance, but other than that looks good!

2021-01-03 23:11 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/combat/movecraftcombat/status/StatusManager.java
> +        if(manOverboard) {
To simplify and streamline the code performance, let's change this to the following format:
```java
if(Config.CombatReleaseBanLength <= 0 && !Config.EnableCombatReleaseKick)
  return;
if(!canOverboard())
  return;
if(Config.CombatReleaseBanLength > 0) {
  // do ban
}
// do kick
```

2021-01-03 23:11 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/combat/movecraftcombat/status/StatusManager.java
> +        Location telPoint = new Location(craft.getW(), telX, telY, telZ);
To simplify this we could merely use craft.getHitBox.getMidpoint, which is an approximation but should be sufficient and much simpler.

2021-01-03 23:11 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/combat/movecraftcombat/status/StatusManager.java
> +        return !(telPoint.distanceSquared(player.getLocation()) > Settings.ManOverboardDistSquared);
To simplify this, `return telpointdistsquared =< settingsdistsquared`.

2021-01-03 23:34 UTC, HumorousFool commented
Requested changes made, I'll make sure to open issues in the future.

2021-01-04 01:12 UTC, TylerS1066 approved these changes

2021-01-04 01:12 UTC, merged