Add an option to re-implement translocation for versions 1.11 and above.
TylerS1066/Movecraft-Combat pull request #49
Opened 2021-03-15 02:37 UTC by HumorousFool

This PR re-implements piston translocation for newer versions.

2021-03-15 05:46 UTC, HumorousFool commented
Do not merge this yet. I have forgotten that tnt gets translocated while inside the piston and will fix this tomorrow.

2021-03-15 17:14 UTC, HumorousFool commented
This is now ready to merge

2021-03-16 02:26 UTC, drfiveminusmint commented
Does this properly check for an air block at the translocating location? Otherwise this is a change in behaviour.

2021-03-16 03:08 UTC, HumorousFool commented
Good catch! I had to do this in a bit of a weird way though.

2021-03-16 06:29 UTC, HumorousFool commented
This isn't gonna work, I'll rethink it tomorrow but I'm open to ideas @drfiveminusmint

2021-03-16 06:45 UTC, HumorousFool commented
After looking at the docs I think I know what to do

2021-03-17 00:48 UTC, HumorousFool commented
Using isSolid is far from perfect but is the best thing I could think of. @TylerS1066 how does this PR look to you?

2021-03-19 01:35 UTC, TylerS1066 requested changes
Maybe I wasn't clear enough in my previous post on #46 .  For features which are directly spawned from the Airship Pirates server, please go through the appropriate suggestion system to get them implemented.  I thank you for your contributions and willingness to code things, but if you want to help the Airship Pirates server progress, your time is best spent coding things which have already been approved.

I understand the want to make suggestions on features, and I still welcome you to make suggestions and mention that you are willing to code them (since that will increase the chances of it being discussed and implemented), but that needs to happen before you open a PR.


Regardless, we may be interested in this, and if we do there are many problems with this that show that it was untested and with minimal research into the Spigot API.  I've commented with all the ones I've noticed so far.

2021-03-19 01:35 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/combat/movecraftcombat/MovecraftCombat.java
> +        Config.ReImplementTranslocation = getConfig().getBoolean("ReImplementTranslocation", false);
This should only be enabled if the version is above 1.10.

2021-03-19 01:35 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/combat/movecraftcombat/MovecraftCombat.java
> +        getServer().getPluginManager().registerEvents(new PistonListener(), this);
Same here.

2021-03-19 01:35 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/combat/movecraftcombat/config/Config.java
> +    public static boolean ReImplementTranslocation = false;
This should be renamed to ReImplementTNTTranslocation, since it is not general translocation.

2021-03-19 01:35 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/combat/movecraftcombat/listener/PistonListener.java
> +        Location moveLocation = e.getBlock().getLocation().add(direction);
You can use e.getBlock().getRelative(e.getDirection()) to simplify the head location.

Similarly, you can use e.getDirection().getOppositeFace() to get the moveLocation.  You'll still need to add 0.5 to get the correct center of the block location.

2021-03-19 01:35 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/combat/movecraftcombat/listener/PistonListener.java
> +        if(moveLocation.getBlock().getType().isSolid())
isSolid() is not in all API versions, use `isEmpty() || isLiquid() || getType().getName().contains("SIGN")`.  It won't cover 100% of usage cases but will cover 99% of them.

2021-03-19 01:35 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/combat/movecraftcombat/listener/PistonListener.java
> +            if(!ent.getLocation().getBlock().getLocation().equals(headLocation) &&
So many calls to getLocation().getBlock().getLocation(), store it above and check against it here.

2021-03-19 01:35 UTC, TylerS1066 commented on src/main/resources/config.yml
> +ReImplementTranslocation: false
This should have a comment to describe what it does and that it only works on 1.11+.

2021-03-19 14:33 UTC, drfiveminusmint commented
In addition, a couple of bugs from testing:
1. The position of TNT is off by 0.5 when translocating in negative directions
2. Does not appear to work with sticky pistons
3. Translocating is blocked by a bunch of things that really shouldn't block it, such as signs, torches etc.

2021-03-28 02:23 UTC, closed without merging

2021-03-28 02:24 UTC, TylerS1066 commented
Due to no updates, this is being closed.

If we wish to implement this feature, we will code it outselves.