Improved Contact Explosives
TylerS1066/Movecraft-Combat pull request #76
Opened 2021-07-06 16:18 UTC by drfiveminusmint

The contact explosives system was designed to prevent ships with completely flat sides from becoming dominant, but with the advent of cannon directors we have seen a similar thing crop back up. This PR makes some slight improvements to the contact explosive code as well as making the sensitivity configurable.

2021-07-06 16:19 UTC, drfiveminusmint commented
As a brief side note, the default Contact Explosives sensitivity has been unchanged, but I would personally recommend values in the range of `2.0` for most servers.

2021-07-06 21:14 UTC, TylerS1066 requested changes
Looks good, just needs some documentation.


Do you have a simple test setup to verify this is functioning?

2021-07-06 21:14 UTC, TylerS1066 commented on src/main/resources/config.yml
> +ContactExplosivesMaxImpulseFactor: 10.0
We should have a description of what this is.

2021-07-06 21:22 UTC, drfiveminusmint commented
> Looks good, just needs some documentation.
> 
> Do you have a simple test setup to verify this is functioning?

An example test setup would be to fire a cannon at a wall that is parallel to its flight path and a certain distance to the side, like so.
![2021-07-06_17 21 15](https://user-images.githubusercontent.com/52045376/124668265-98754580-de7e-11eb-952f-28e486e5207b.png)

At higher values (like the default of 10) it should almost always slide down the side, whereas at a value of, say, 2, it should detonate at sharper angles.

2021-07-17 20:50 UTC, TylerS1066 commented
Compiled this, installed it on my testing server, immediately set the ratio to 1.0, and watched as everything had problems....


Once the ID10T error was resolved, this works great!   Once switched over to a 2.0 ratio it promptly exploded on a sliding wall like shown.

2021-07-17 20:50 UTC, TylerS1066 approved these changes

2021-07-17 20:50 UTC, merged